# name of the software
name: AVChat Standalone
# current version of the software
version: 3.7.2
# url of the download button
downloadUrl: http://avchat.net
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jekyll-bootstrap-doc
  - title: Issues
    url: https://github.com/mistic100/jekyll-bootstrap-doc/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: mistic100
  repo: jekyll-bootstrap-doc

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
